name: new-release

on: push

jobs:
  build:
    name: generate-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          npm install
      - name: Build
        run: bundle exec middleman build
      - name: Release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bin/github-release --version "${GITHUB_SHA::7} publish"
      - name: Trigger pay-frontend
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -XPOST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            --data '{"event_type": "product-page-release"}' \
            https://api.github.com/repos/alphagov/pay-frontend/dispatches
